server:
  port: 9001

spring:
  application:
    name: service1

eureka:
  client:
    service-url:
      default-zone: http://${spring.cloud.client.ip-address}:8761/eureka/
  instance:
    prefer-ip-address: true